"""add digest retry key

Revision ID: 48d7e6b888dd
Revises: 2cb032fd8479
Create Date: 2026-10-07 01:45:18.222926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48d7e6b888dd"
down_revision: str | Sequence[str] | None = "2cb032fd8479"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("digests", sa.Column("retry_key", sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("digests", "retry_key")
    # ### end Alembic commands ###
